import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-800 w-full h-full text-gray-100">
        <h1 className="text-2xl font-bold">Test!!!</h1>
        <Image src="/vercel.svg" width="72" height="72" />
      </main>
    </>
  );
};

export default Home;
