// import type { NextPage } from "next";
import Head from "next/head";
import { prisma } from "../db/client";

export default function Home(props: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full h-full">
        <h1 className="text-2xl font-bold">Test!!!</h1>
        <code>{props.games}</code>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const games = await prisma.game.findMany();

  return {
    props: {
      games: JSON.stringify(games),
    },
  };
};
